ZONES = ['Blood Moor Den of Evil',
         'Cold Plains The Cave',
         'Burial Grounds The Crypt the Mausoleum',
         'Stony Field', 'Dark Wood Underground Passage',
         'Black Marsh The Hole', 'The Forgotten Tower',
         'Jail  Barracks', 'Cathedral Catacombs',
         'The Pit', 'Tristram', 'Moo Moo Farm',
         'Sewers', 'Rocky Waste Stony Tomb',
         'Dry Hills Halls of the Dead', 'Far Oasis',
         'Lost City Valley of Snakes Claw Viper Temple',
         'Ancient Tunnels',
         'Arcane Sanctuary',
         "Tal Rasha's Tombs",
         'Spider Forest Spider Cavern',
         'Great Marsh', 'Flayer Jungle Flayer Dungeon',
         'Kurast Bazaar Ruined Temple Disused Fane', 'Travincal',
         'Durance of Hate', 'Outer Steppes Plains of Despair',
         'River of Flame City of the Damned', 'Chaos Sanctuary',
         'Bloody Foothills  Frigid Highls Abbadon',
         'Glacial Trail  Drifter Cavern', 'Crystalline Passage Frozen River',
         'Arreat Plateau  Pit of Acheron', "Nihlathak's Temple Halls of Anguish Halls of Pain Halls of Vaught",
         "Ancient's Way Icy Cellar", 'Worldstone Keep Throne of Destruction Worldstone Chamber']
