ZONES = {
    1: 'Blood Moor Den of Evil',
    2: 'Cold Plains The Cave',
    3: 'Burial Grounds The Crypt the Mausoleum',
    4: 'Stony Field',
    5: 'Dark Wood Underground Passage',
    6: 'Black Marsh The Hole',
    7: 'Forgotten Tower',
    8: 'Jail  Barracks',
    9: 'Cathedral Catacombs',
    10: 'Pit',
    11: 'Tristram',
    12: '🐮 Moo Moo Farm',
    13: 'Sewers',
    14: 'Stony Tomb Rocky Waste',
    15: 'Dry Hills Halls of the Dead',
    16: 'Far Oasis',
    17: 'Lost City Valley of Snakes Claw Viper Temple',
    18: 'Ancient Tunnels',
    19: 'Arcane Sanctuary',
    20: "Tal Rasha's Tombs",
    21: 'Spider Forest Spider Cavern',
    22: 'Great Marsh',
    23: 'Flayer Jungle Flayer Dungeon',
    24: 'Kurast Bazaar Ruined Temple Disused Fane',
    25: 'Travincal',
    26: 'Durance of Hate',
    27: 'Outer Steppes Plains of Despair',
    28: 'River of Flame City of the Damned',
    29: 'Chaos Sanctuary',
    30: 'Bloody Foothills  Frigid Highls Abbadon',
    31: 'Glacial Trail  Drifter Cavern',
    32: 'Crystalline Passage Frozen River',
    33: 'Arreat Plateau  Pit of Acheron',
    34: "Nihlathak's Temple Halls of Anguish Halls of Pain Halls of Vaught",
    35: "Ancient's Way Icy Cellar",
    36: 'Worldstone Keep Throne of Destruction Worldstone Chamber'
}
